#!/bin/sh

qmake -set ZINT_INSTALL_LIBS /Library/Frameworks
qmake -set ZINT_INSTALL_HEADERS  /eXaro/include

qmake -set QUAZIP_INSTALL_LIBS /Library/Frameworks
qmake -set QUAZIP_INSTALL_HEADERS  /eXaro/include

qmake -set EXARO_INSTALL_BINS /eXaro
qmake -set EXARO_INSTALL_LIBS /Library/Frameworks
qmake -set EXARO_INSTALL_HEADERS  /eXaro/include
qmake -set EXARO_INSTALL_PLUGINS /eXaro/exaro/PlugIns

qmake -set EXARO_INSTALL_TRANSLATIONS  /eXaro/exaro/Resources/translations

cd libs
qmake -recursive -spec macx-g++ && make -j2 && make install
cd ../plugins
qmake -recursive -spec macx-g++ && make -j2 && make install
cd ../apps
qmake -recursive -spec macx-g++ && make -j2 && make install
cd ..
cp -pR `qmake -query EXARO_INSTALL_PLUGINS` `qmake -query EXARO_INSTALL_BINS`/exaro.app/Contents 
